### ISSUE TITLE
Extra space in the format name

### ISSUE THREAD

**Issue by nkrabben** [NYPL/ami-metadata#144]
Not sure if this matters,

https://github.com/NYPL/ami-metadata/blob/dc8e117fba1eda1cef90f6190bbe69a36dda939e/versions/2.0/schema/digitized_audiofilm.json#L92

**Comment by genfhk** [comment]
filed JIRA ticket for CMS: https://jira.nypl.org/secure/RapidBoard.jspa?rapidView=107&projectKey=PRES&selectedIssue=PRES-171
awaiting fix.

**Comment by genfhk** [comment]
Fixed!
