### ISSUE TITLE
Can schemaVersion support semantic versioning?

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL/ami-metadata#4]
Hey @nkrabben .

I see in `fields.json`:

```javascript
  "schemaVersion": {
    "type": "number",
    "multipleOf": 1.0
   }
```

That stops us from using Semantic Versioning.
For example - if we used version 1.7:

```
ajv validate -s schema/digitized_audioreel.json -r schema/fields.json -d sample/sample_digitized_audioreel.json
sample/sample_digitized_audioreel.json invalid
[ { keyword: 'multipleOf',
    dataPath: '.asset.schemaVersion',
    schemaPath: 'fields#asset/properties/schemaVersion/multipleOf',
    params: { multipleOf: 1 },
    message: 'should be multiple of 1' } ]
```

I'm fine with this being a string so we can do things like "1.7.1" or a decimal.
I know the first batch of assets we'll get back from vendors will be 1.0, but I think giving ourselves wiggle room for semver (or at least numeric decimal) will pay off.

**Comment by nodanaonlyzuul** [comment]
Sorry - one more related request.
When we tag release versions...can the example `.json` files be in the specified version.

For example:
It would be great if the example JSON files in the [0.4 release](https://github.com/NYPL/ami-metadata/tree/v0.4/sample) had `schemaVersion`s of 0.4.

I could even see us using a controlled dictionary of only that value.

For example:
For release 0.4 `schemaVersion` could be limited to only be valid for 0.4.

**Comment by nkrabben** [comment]
schemaVersion now look for a pattern currentMajorVersion\.{0-currentMinorVersion}\.\d+
