### ISSUE TITLE
requirements differ among digital video cassette formats

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-metadata#56]
digitization workflow for digital video cassettes captured using an SDI-based signal path will incorporate use of a TBC (built into the payback device or otherwise); tapes will not necessarily have defined audio bit depth's or sampling rates. 

_digitized_videocassettedigital.json_ does not currently accommodate these differences among DV and non-DV video formats.

**Comment by genfhk** [comment]
Resolved: 
additional TBC information will be included by vendors in **digitizationProcess.notes.processNotes.**

+ [Pull # 57 - audioBitDepth & audioSamplingRate made Optional](https://github.com/NYPL/ami-metadata/pull/57)

**Comment by nkrabben** [comment]
We can add the TBC field chunk into the digitization process section as an optional

**Comment by nkrabben** [comment]
Thoughts about including the digitizationProcess.tbc fields as optional in the schema, or should we close this?

**Comment by nkrabben** [comment]
Addressed in PR86
