### ISSUE TITLE
tapeSpeed: add "multiple" for tapes recorded at varying speeds on different regions?

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-metadata#65]

**Comment by nkrabben** [comment]
I feel it would be more accurate to mark the speed used in each metadata file for each region file.

**Comment by genfhk** [comment]
How would one identify that the field source.object.tapeSpeed then refers to only the tape speed on that region of the source tape? In the past we have literally said to the vendors "source.object information should not differ between files - that information stays the same because each file comes from the same tape". So, I guess I'm wondering if we are changing/updating the definition of source.object from "the physical object" (singular) to "the physical areas on the object" (multiple). This would also then apply to video broadcast standard.

**Comment by nkrabben** [comment]
Source contains both object and subobject. Every source section should already identify which subject it is describing.
