### ISSUE TITLE
Is h264 the right value for this field?

### ISSUE THREAD

**Issue by nkrabben** [NYPL/ami-metadata#67]
https://github.com/NYPL/ami-metadata/blob/master/versions/2.0/schema/fields.json#L181

Most of the service copies we're receiving states that it's "avc1" which is in capture spec and metadata spec, just from a different field in mediainfo

**Comment by bturkus** [comment]
we should prob close some of these out too

**Comment by genfhk** [comment]
resolved by allowing more values to accommodate dif mediainfo pulling across inhouse and vendor...
