### ISSUE TITLE
subObjectWithoutStreams optional for video but requires "faces" (which videos do not have)

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-metadata#83]

**Comment by genfhk** [comment]
Clarifying question: If a video has regions, must it also define faces?

**Comment by nkrabben** [comment]
Good question. It doesn't seem like it should. Faces are only relevant for optical discs. `subObjectWithoutStreams` can apply to that, and we can create a third `subObject...` definition for streamless, faceless video.

**Comment by nkrabben** [comment]
`subObjectWithoutStreams` is also used for a couple of audio format types, so we should definitely keep that object, maybe rename it.

**Comment by genfhk** [comment]
agreed. I'll create a new issue for creating a new subObject.
