### ISSUE TITLE
Create film schema

### ISSUE THREAD

**Issue by nkrabben** [NYPL/ami-metadata#88]

**Comment by nkrabben** [comment]
@genfhk I started a branch for this work, initial json file is here but a lot of the vocab lists are empty. We also need to create a sample file and add the schema to digitized.json.

https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json

**Comment by nkrabben** [comment]
Empty vocab lists
noise reduction: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L282
sync tone: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L292
lamp: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L341
transport: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L346

Fields that need more exact bounds
frame rate measure: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L240
shrinkage: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L196
length: https://github.com/NYPL/ami-metadata/blob/film/versions/2.0/schema/digitized_film.json#L175

**Comment by genfhk** [comment]
Film schema created and essentially complete? Any new issues can be new issues.
